@Host = http://localhost:3000

POST {{Host}}/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "yang",
  "password": "123456"
}

### Get User

GET {{Host}}/api/user HTTP/1.1

###

POST {{Host}}/api/user HTTP/1.1
Content-Type: application/json

{
  "username": "yang",
  "name": "Yang",
  "password": "123456"
}
